[build]
 command = "yarn build"
 functions = "functions"
 publish = "[subdirectory folder name]/build"
 base = "[subdirectory folder name]"
 [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

   